name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sdl2:x64-linux

    - name: Build Linux
      run: |
        cmake -B build-linux -S . \
          -GNinja \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build-linux

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: build-linux/bin/*

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build mingw-w64

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sdl2:x64-mingw-dynamic

    - name: Build Windows
      run: |
        cmake -B build-windows -S . \
          -GNinja \
          -DTARGET_WINDOWS=ON \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build-windows

    - name: Debug Build Output
      run: |
        echo "Listing build-windows directory:"
        ls -R build-windows/
        echo "Listing build-windows/bin directory (if exists):"
        ls -R build-windows/bin/ || echo "bin directory not found"

    - name: Prepare Windows Package
      run: |
        # Create deployment directory
        mkdir -p deploy/windows
        
        # Check if files exist before copying
        if [ -d "build-windows/bin" ] && [ "$(ls -A build-windows/bin/)" ]; then
          echo "Copying build files..."
          cp build-windows/bin/*.exe deploy/windows/ || echo "No .exe files found"
          cp build-windows/bin/*.dll deploy/windows/ || echo "No .dll files found"
        else
          echo "Error: build-windows/bin directory is empty or doesn't exist"
          exit 1
        fi
        
        # Find MinGW DLLs
        MINGW_PATH=$(dirname $(which x86_64-w64-mingw32-g++))/../x86_64-w64-mingw32
        echo "MinGW Path: $MINGW_PATH"
        ls -R $MINGW_PATH/lib/
        
        # Copy MinGW DLLs with verbose output
        echo "Copying MinGW DLLs..."
        find $MINGW_PATH -name "libstdc++-6.dll" -exec cp {} deploy/windows/ \; -print || echo "libstdc++-6.dll not found"
        find $MINGW_PATH -name "libgcc_s_seh-1.dll" -exec cp {} deploy/windows/ \; -print || echo "libgcc_s_seh-1.dll not found"
        find $MINGW_PATH -name "libwinpthread-1.dll" -exec cp {} deploy/windows/ \; -print || echo "libwinpthread-1.dll not found"
        
        # Create test batch file
        echo "Creating test batch file..."
        echo "@echo off" > deploy/windows/test.bat
        echo "echo Testing SDL2 Application" >> deploy/windows/test.bat
        echo "cross_platform_example.exe" >> deploy/windows/test.bat
        echo "pause" >> deploy/windows/test.bat
        
        # Check final package contents
        echo "Final package contents:"
        ls -R deploy/windows/
        
        # Create ZIP file
        cd deploy/windows
        zip -r ../windows-build.zip * || echo "ZIP creation failed"

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: deploy/windows-build.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: linux-build
        path: linux-build

    - uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: windows-build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          linux-build/*
          windows-build/windows-build.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive builds
      if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: all-builds
        path: |
          linux-build/*
          windows-build/windows-build.zip