name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sdl2:x64-linux

    - name: Build Linux
      run: |
        cmake -B build-linux -S . \
          -GNinja \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build-linux

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: build-linux/bin/*

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build mingw-w64

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sdl2:x64-mingw-dynamic

    - name: Build Windows
      run: |
        cmake -B build-windows -S . \
          -GNinja \
          -DTARGET_WINDOWS=ON \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build-windows
        
    - name: Prepare Windows Package
      run: |
        mkdir -p deploy/windows
        
        # Copy build outputs
        cp build-windows/bin/*.exe deploy/windows/
        cp build-windows/bin/*.dll deploy/windows/
        
        # Copy SDL2 dependencies from vcpkg
        cp $VCPKG_ROOT/installed/x64-mingw-dynamic/bin/SDL2.dll deploy/windows/
        
        # Copy MinGW runtime DLLs
        cp /usr/lib/gcc/x86_64-w64-mingw32/*/libstdc++-6.dll deploy/windows/ || true
        cp /usr/lib/gcc/x86_64-w64-mingw32/*/libgcc_s_seh-1.dll deploy/windows/ || true
        cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll deploy/windows/ || true
        
        # Create a more detailed test batch file
        echo "@echo off" > deploy/windows/run_test.bat
        echo "echo Starting application..." >> deploy/windows/run_test.bat
        echo "echo Current directory:" >> deploy/windows/run_test.bat
        echo "cd" >> deploy/windows/run_test.bat
        echo "echo Files in directory:" >> deploy/windows/run_test.bat
        echo "dir" >> deploy/windows/run_test.bat
        echo "echo." >> deploy/windows/run_test.bat
        echo "echo Running application..." >> deploy/windows/run_test.bat
        echo "cross_platform_example.exe" >> deploy/windows/run_test.bat
        echo "if errorlevel 1 (" >> deploy/windows/run_test.bat
        echo "  echo Application failed with error code %errorlevel%" >> deploy/windows/run_test.bat
        echo "  pause" >> deploy/windows/run_test.bat
        echo ")" >> deploy/windows/run_test.bat
        echo "pause" >> deploy/windows/run_test.bat
        
        # List all files
        echo "Final package contents:"
        ls -l deploy/windows/
        
        cd deploy/windows
        zip -r ../windows-build.zip *

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: deploy/windows-build.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    # Only run this job when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Linux Artifact
      uses: actions/download-artifact@v3
      with:
        name: linux-build
        path: artifacts/linux-build

    - name: Download Windows Artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: artifacts/windows-build

    - name: Prepare Release Files
      run: |
        mkdir -p release-files
        cp artifacts/linux-build/* release-files/
        cp artifacts/windows-build/windows-build.zip release-files/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-files/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
