name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sdl2:x64-linux

    - name: Build Linux
      run: |
        cmake -B build-linux -S . \
          -GNinja \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build-linux

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: build-linux/bin/*

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build mingw-w64

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sdl2:x64-mingw-dynamic

    - name: Build Windows
      run: |
        cmake -B build-windows -S . \
          -GNinja \
          -DTARGET_WINDOWS=ON \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build-windows

    - name: Debug Build Output
      run: |
        echo "Listing build-windows directory:"
        ls -R build-windows/
        echo "Listing build-windows/bin directory (if exists):"
        ls -R build-windows/bin/ || echo "bin directory not found"

    - name: Prepare Windows Package
      run: |
        mkdir -p deploy/windows
        
        # Copy build outputs
        cp build-windows/bin/*.exe deploy/windows/
        cp build-windows/bin/*.dll deploy/windows/
        
        # Copy MinGW DLLs - using a different approach to find them
        MINGW_BIN=/usr/lib/gcc/x86_64-w64-mingw32/*-posix
        echo "MinGW bin path: $MINGW_BIN"
        cp $MINGW_BIN/libstdc++-6.dll deploy/windows/
        cp $MINGW_BIN/libgcc_s_seh-1.dll deploy/windows/
        
        # Alternative path for pthread
        cp /usr/x86_64-w64-mingw32/lib/libwinpthread-1.dll deploy/windows/
        
        # List what we copied
        echo "Final package contents:"
        ls -l deploy/windows/
        
        # Create test batch file
        echo "@echo off" > deploy/windows/test.bat
        echo "echo Testing SDL2 Application" >> deploy/windows/test.bat
        echo "cross_platform_example.exe" >> deploy/windows/test.bat
        echo "pause" >> deploy/windows/test.bat
        
        cd deploy/windows
        zip -r ../windows-build.zip *

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: deploy/windows-build.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    # Only run this job when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download Linux Artifact
      uses: actions/download-artifact@v3
      with:
        name: linux-build
        path: artifacts/linux-build

    - name: Download Windows Artifact
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: artifacts/windows-build

    - name: Prepare Release Files
      run: |
        mkdir -p release-files
        cp artifacts/linux-build/* release-files/
        cp artifacts/windows-build/windows-build.zip release-files/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-files/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
